### ISSUE TITLE
Ideen 

### ISSUE THREAD

**Issue by bszetprint** [fxsth/pledo#10]
Hey fxsth, dein Projekt ist wirklich klasse und läuft stabiler wie so manch ein anderes Programm.

Mich würde es freuen, wenn die dir mal die folgenden Ideen anschauen würdest:

- Wenn Downloads gecancelt oder einen Error bekommen, sollte das File gelöscht werden.
- Folgende Atribute fände ich im WEBUI ganz nützlich
```
"videoCodec":"hevc"
"videoResolution":"1080"
"size":261479003"
```
 - Und eine Option zum Downloaden einer Playlist wie in folgenden Repo https://github.com/evolve700/PlexPlaylistDownload wäre spitzenklasse.
 
 Danke für deine Zeit...

**Comment by fxsth** [comment]
Hi bszetprint,
danke für die Ideen! Die Features kommen auf die Todo-Liste und werden implementiert, sobald ich Zeit finde.

**Comment by fxsth** [comment]
Die Features sind nun in Version 1.1.0 umgesetzt.
