### ISSUE TITLE
persistency of the settings and download progress in docker

### ISSUE THREAD

**Issue by GeirMydland** [fxsth/pledo#11]
Hi 
I'd like the possibility to have persistency of the settings data and download progress defined in a volume in docker. Thus one could restart the container and not have to define the settings and redo downloads that have been dropped during a restart.

**Comment by fxsth** [comment]
I agree, this is a useful feature. It will be in the next release.
I should keep track of breaking changes in database by now...

**Comment by GeirMydland** [comment]
Awesome, thanks for that information.
