### ISSUE TITLE
Server list empty

### ISSUE THREAD

**Issue by cyrinux** [fxsth/pledo#14]
Hi,
Thanks for this program 😃 
This looks like exactly what I was searching, but after settings it (with docker-compose), I log to my plex, set settings movies and tvshows dir, but then, I can see nothing, my server list is empty, any idea ?

![image](https://github.com/fxsth/pledo/assets/519083/f6aab55e-2769-4ee9-b6a0-b360cc52e6b8)

**Comment by fxsth** [comment]
Hi, did you sync all metadata after logging in?
If there is still an issue with synced server, please try again with the new release v1.2.0 (docker image is building right now).

**Comment by cyrinux** [comment]
It works ! Thanks !
