### ISSUE TITLE
Is it possible to add a download to browser feature ?

### ISSUE THREAD

**Issue by cyrinux** [fxsth/pledo#15]
My bad, I misunderstand the main usage of the app maybe, would it be possible to download in the browser the file instead of just copy on the server side ? 

I would like to time to time share movie with people who just want to download and watch locally without plex. 

In the case the people is not tech and can't selfhost pledo on his side.

Cheers

**Comment by fxsth** [comment]
Unfortunately it is not a regular desktop app, but a backend with web frontend.
Closest to a desktop app are the windows executable in https://github.com/fxsth/pledo/releases/tag/v1.2.0
You can start the pledo.exe and navigate browser to localhost:5000.

**Comment by fxsth** [comment]
Ah probably I misunderstood your feature request as well.
Do you want to host the app for your friends and they can access the web app? So they have a download button for downloading to browser?

**Comment by cyrinux** [comment]
Exactly yes

**Comment by fxsth** [comment]
I'll try to add this in the next time. Shouldn't be that complicated to add a download link for browser.

**Comment by fxsth** [comment]
Upcoming release has the feature to open and download the file link directly in browser.

**Comment by cyrinux** [comment]
Thanks you very much, it make the job as I expected 🧁
