### ISSUE TITLE
Download Immediately Cancelled

### ISSUE THREAD

**Issue by tvillini** [fxsth/pledo#16]
When I try to download from a friend's library, it shows as cancelled immediately. I'm not really sure what the issue is, and don't really know where to find the logs to triage the issue. I thought for a bit it might be an issue of rights to the storage, but I attached to the docker container and was able to see the storage mounted and writable. I also DID try to download from my own library, and that was successful. It's just an issue from a friend's library. Thanks for any help!

**Comment by tvillini** [comment]
I did. I can try again, but I even tried wiping the database, and starting a fresh docker container just to make sure.

**Comment by fxsth** [comment]
I figured out that a download request on some connection uris (namely 'plex.direct'-Uris) return a bad request response, even when syncing with this uri is totally fine. So the downloader is now considerung direct connections with http uris and even trying different ones when the selected one is not working.
You can try out the latest release 1.3.0, I'm hopeful that it will fix your problem.

**Comment by tvillini** [comment]
Same issue.

￼

However the direct download DOES work. Also, the logging shows more stuff on the regular download:
￼

Thanks!

**Comment by fxsth** [comment]
Unfortunately the send attachments like logs in your comment are not readable...

**Comment by tvillini** [comment]
![image](https://github.com/fxsth/pledo/assets/28534987/01aeebd0-0633-44a8-8665-d46518af9bb8)
![image](https://github.com/fxsth/pledo/assets/28534987/55e6c89d-70f5-415d-b166-b2bf62774bca)

**Comment by fxsth** [comment]
Thanks, that is helping. Seems that there is an issue with the created filename that is derived from original filename at the source media server. Linux and Windows directory seperator are mixed up, when running pledo on linux and the plex media server on windows: '/media/Y:\Movies\BlackBerry (2023).mkv'.
Will be fixed right away.

**Comment by fxsth** [comment]
Fixed on 1.3.1

**Comment by tvillini** [comment]
Thank you, that worked!!
