### ISSUE TITLE
how do I use this?? how do I get to the user interface? what do I need to put in a web browser or in plex to be able to use this

### ISSUE THREAD

**Issue by soundtechscott** [fxsth/pledo#20]
First off...sorry, I am very new to docker

I am a windows user, not a linux user
but I am using the docker for windows...

what do I do to get a user interface to select files to download?
do I go to my web browser? is there something I need to add to plex?
is it a localhost command?

how do I get to this example??
some setup and usage instructions would be useful
![image](https://github.com/fxsth/pledo/assets/51548286/2dcfd680-75ce-4b7a-800c-7ba98daf1322)

**Comment by fxsth** [comment]
Hi,
if you didn't use docker (compose) before, I'd recommend you'll use the windows executable from https://github.com/fxsth/pledo/releases/tag/v1.2.0. Download and extract pledo.win-x64.zip and run the exe, then you can open the user interface in the browser on localhost:5000. Beware, this will first get a warning screen from Windows as it is an app from unknown source.
If you want to use docker, save the docker-compose snippet from the Readme in a file called docker-compose.yml and replace the paths /media/Movies and /media/TvShows by the folder path you want to store the downloaded files. Open powershell/cmd in the directory of the file. Run the command docker-compose up and it will download and start the container on port 23456 as it is configured in the docker-compose snippet. You can now open the user interface in the browser on localhost:23456.

**Comment by soundtechscott** [comment]
I'm getting downloads that have cancelled on their own for no apparent reason...
I cant try again because its already in my download list...
how do I clear the download list to try again?

**Comment by fxsth** [comment]
It may be the same issue as #16.
Latest release v1.3.0 has several improvements, that will make the download more resilient and it might fix your problem as well.
