### ISSUE TITLE
Movie list totally empty

### ISSUE THREAD

**Issue by cyrinux** [fxsth/pledo#22]
Hi !
I start using https://metamanager.wiki/en/latest/  recently, and since, my movie list is totally empty in pledo (with last version 1.3.0 also)). I don't touch TV show library and this one is still OK.

I can't find interesting log, hint, trace to know what is the problem. 
I have this line that say there is 0 movie, its wrong.

`pledo  |       Syncing movies: Found 0 movies in library Movies from server REDACTED`

Is it possible that now my movie "entry" are too huge, contains too much metadata?

Do you have any idea for debugging this? 

Thanks

**Comment by fxsth** [comment]
Strange, this is kind of similiar to #13. 
Your assumption could be possible, the sync requests movies and tv shows in batches, with a batch size of 200 movies with one request. Maybe this exceeds plex media servers limits on movies with too much metadata. I'll think about a different, more dynamic approach.

**Comment by fxsth** [comment]
Metadata sync is now in smaller batches and kind of concurrently, so it shouldn't even be slower than before. Do you mind do try the new version 1.3.1 again?

**Comment by cyrinux** [comment]
It works ! Thanks 💯 🥇
