### ISSUE TITLE
Feature Request - Clear Download History and ability to prioritize downloads

### ISSUE THREAD

**Issue by soundtechscott** [fxsth/pledo#25]
2 things that would be really really nice...

the ability to clear the download list/history
completed downloads go don to the bottom?? and my download list has gotten quite long....
would be nice to be able to clear the completed/cancelled list (or if there is a file to delete/edit to clean the list up manually)

and it would be really great to be able to prioritize downloads / re-order them
have a list already going.... want to download something next, but dont want to have to cancel all the other downloads to move something up in the list to download it next (or if there is a file that stores the list that we could re-order it manually when desired)

**Comment by soundtechscott** [comment]
as far as "download in the right order to start with"......
its not that simple
sometimes you get asked by your significant other to grab a certain movie to watch later that evening, or the other plex server adds a movie that you want to watch and you already have others in your download que.

I am on 1.3.1 and do not see a button to clear downloads anywhere

**Comment by fxsth** [comment]
Do you use docker or the windows executable?

**Comment by soundtechscott** [comment]
Docker

⁣Get BlueMail for Android ​

**Comment by fxsth** [comment]
You should see a button on latest release, maybe you‘re still on 1.3.0.
If you use the docker-compose snippet with pledo:latest than try docker-compose pull, which will update to latest image. Then start again by docker-compose up

**Comment by soundtechscott** [comment]
Thanks
