### ISSUE TITLE
Can't get done with UnRAID

### ISSUE THREAD

**Issue by pelisdev** [fxsth/pledo#28]
I'm having some issues creating the docker on unraid, anyone have installed succesfully on unraid? Can't assign the IP, or Config folder, or custom port number, on Windows is working well.

**Comment by fxsth** [comment]
I'm not familiar with UnRAID, sorry.

**Comment by Whitedoteu** [comment]
HI I used Docker-Compose Plugin on Unraid. 
https://docs.ibracorp.io/docker-compose/docker-compose-for-unraid
Works great.

**Comment by pelisdev** [comment]
Thanks for the suggestion, i will give it a try!
