### ISSUE TITLE
Feature Request - *Arr integration.

### ISSUE THREAD

**Issue by reg98643t** [fxsth/pledo#38]
Would be a killer feature for this, many of us have friends with their own selfhosted streaming and it would be great to be able to "borrow" content from each other as a last resort when the other download options fail.

**Comment by fxsth** [comment]
I'd love to implement this feature - but unfortunately it won't work that way. 
Theoretically, pledo could be an *arr indexer and returning media information (name, resolution, category, download link) to Radarr/Sonarr that will request a download client to download it. Unfortunately *arr uses .nzb or .torrent files for information about binary data location and both are based heavily on the usenet or torrent protocol as they cannot carry an http direct link.
Apart from usenet and torrent, the *arr ecosystem does not support any other filesharing system.
