### ISSUE TITLE
Improvement Ideas

### ISSUE THREAD

**Issue by alafad** [fxsth/pledo#6]
Hello fxsth, i found your project, because plexripper has a few problem like a OOM error while downloading a few things .

Now i have a found your pretty cool app is it possible to bulk download a TVshow with one click (all Episodes and Seasons).

Another cool feature would be great, if I can create a watchlist in the original Plex app and the downloader will download from these.

Thanks you

**Comment by fxsth** [comment]
Hey and thanks - these are some cool ideas!
The bulk download for tv shows will be implemented soon.
Regarding the watchlist feature: Do you mean bulk download a watchlist (manually) or setting up the downloader to watch the watchlist and download recently added items automatically?

**Comment by alafad** [comment]
> Hey and thanks - these are some cool ideas!
> The bulk download for tv shows will be implemented soon.
> Regarding the watchlist feature: Do you mean bulk download a watchlist (manually) or setting up the downloader to watch the watchlist and download recently added items automatically?

I mean the last option, that I can create a (Watch)-Downloadlist with the better interface of the plex.tv UI.

That could be a good way to avoid the many Tasks and Problems to create a own UI for choosing the media for downloading, by an actor, Year or implement a search.

That's only a Idea, I don't have any practical experience, but I think this would be a good solution.

**Comment by fxsth** [comment]
I think it's possible but I'll have to think about it how to implement this (and find some time too).
Meanwhile, I'll make an intermediate release with bulk downloads for tv shows as it is a smaller feature with less effort than the watchlist.

**Comment by alafad** [comment]
I maked a research for the playlist solution and I have found the [following](https://github.com/evolve700/PlexPlaylistDownload) project. Unfortunately the download doesnt works for me, but it might can help for an playlist download.

**Comment by fxsth** [comment]
Downloading playlists (manually) is now a feature of release v1.1.0. 
I discarded the idea of the automatic watchlist thingy as it would come along with some unwanted complexity.
